# Link the C runtime statically, so the exe runs on a clean Windows install
# without the Visual C++ redistributable. build.rs compiles the C++ side with
# /MT to match.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
