[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
upload_protocol = picotool
upload_port = COM4
monitor_speed = 115200
extra_scripts = upload_script.py
